name: Format and Test

on:
  push:
    branches-ignore:
      - main  # Avoid running on main since validation is handled separately

jobs:
  format-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the PR branch
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements
        pip install black flake8 pytest

    # Step 4: Format Code (but do not fail)
    - name: Format Code
      run: black .

    # Step 5: Run Linter (warn only, does not fail)
    - name: Lint with Flake8 (warn only)
      run: flake8 . || true  # Allows warnings without failing the pipeline

    # Step 6: Run Tests
    - name: Run Tests
      run: pytest
